# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - test
  - coverage
  - release

include:
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/common/conventional-commits.v1.yml
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/python/pytest-meta.v1.yml
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/python/pypi.v1.yml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

Pre-commit:
  stage: lint
  interruptible: true
  needs: []
  image: python:3.8
  before_script:
    - pip install --no-cache-dir poetry
    - poetry install
  script:
    - poetry run pre-commit run --all-files

Test:
  extends: .pytest
  variables:
    PYTEST_COV_MODULE: ramqp
    PYTEST_EXTRA_FLAGS: -m unittest

    POETRY_VIRTUALENVS_CREATE: "true"
    POETRY_VIRTUALENVS_IN_PROJECT: "true"

Integration-test:
  extends: .pytest
  services:
    - name: rabbitmq:3
      alias: rabbitmq
  variables:
    PYTEST_COV_MODULE: ramqp
    PYTEST_EXTRA_FLAGS: -m integrationtest

    AMQP_URL: amqp://guest:guest@rabbitmq:5672

    POETRY_VIRTUALENVS_CREATE: "true"
    POETRY_VIRTUALENVS_IN_PROJECT: "true"

Export Integration-test coverage:
  extends: .export_coverage
  needs:
    - Test
    - Integration-test

Check Integration-test coverage:
  extends: .check_coverage
  needs:
    - Test
    - Integration-test
