# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        language: system
        types: [file, python]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
      - id: reuse
