# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    auto-merge: false
    rebase-strategy: all
